# conda env create -f environment.yml
# conda env update -f environment.yml
# conda env remove -n <environment_name>
# conda clean --all

name: dll25-agid
channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip=24.3.1
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.14.1
  - scikit-learn=1.5.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - plotly=6.0.1
  - ipykernel=6.29.5
  - python-dotenv=1.0.1
  - pip:
    - torch==2.6.0
    - torchvision==0.21.0
    - einops==0.8.1
    - wandb==0.19.10
    - fastprogress==1.0.3
    - multiprocess==0.70.18
    - ftfy==6.2.0
    - regex==2023.12.25
    - tqdm==4.66.4
    - Pillow==10.3.0
    - git+https://github.com/openai/CLIP.git
    - imagesize==1.4.1
